/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Btree;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import modelo.CaracteristicasObjPagina;
import modelo.Pagina;
import modelo.Procesador;

/**
 *
 * @author toshiba
 */
public class frmVistaInicial extends javax.swing.JFrame {

    Procesador pr = new Procesador();
    Pagina objEncontrado = new Pagina();

    /**
     * Creates new form frmVistaArbol
     */
    public frmVistaInicial() {
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo1 = new javax.swing.JComboBox();
        panelRam1 = new vista.panelRam();
        jScrollPane1 = new javax.swing.JScrollPane();
        paginaArea = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelRam1Layout = new javax.swing.GroupLayout(panelRam1);
        panelRam1.setLayout(panelRam1Layout);
        panelRam1Layout.setHorizontalGroup(
            panelRam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        panelRam1Layout.setVerticalGroup(
            panelRam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        paginaArea.setEditable(false);
        paginaArea.setColumns(20);
        paginaArea.setRows(5);
        jScrollPane1.setViewportView(paginaArea);

        btnEliminar.setText("Eliminar Objeto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton2.setText("agregar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelRam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void iniciar() {
        pr.procesar();
        llenarComboBox();

    }

    private void llenarComboBox() {

        //System.out.println("no " + nombresDiscos);
        combo1.setBounds(10, 10, 80, 20);

        for (int i = 1; i <= pr.getNombresDiscos().size(); i++) {
            combo1.addItem(i);

        }
        //jComboBox1.addItemListener(this);

    }
    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
     paginaArea.setText("");
        String itemCount;
        itemCount = combo1.getSelectedItem().toString();
        carga(itemCount);


    }//GEN-LAST:event_combo1ItemStateChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // paginaArea.setEditable(true);
        frmEdicion jFrame = new frmEdicion();//2do jframe editar pagina

        jFrame.setVisible(true);
        /*if (jFrame.getObjs()!=null) {
            System.out.println("al if del frame si entra");
            String vecObjs[]=jFrame.getObjs().toString().split(" ");
            for (String o : vecObjs) {
                objEncontrado.pushPila(o);
            }
            paginaArea.setText("");
            carga(""+objEncontrado.getCodigo());
            
            //pr.getArbol().search(objEncontrado.getCodigo()).
        }*/
        System.out.println("salto el if");

    }//GEN-LAST:event_jButton2ActionPerformed
    private void cargarRam(Pagina objPagina) {
        String aux = "";
        
        for (int i = objPagina.getObjetosPila().size() - 1; i >= 0; i--) {
            //llama al metodo push de la ram donde empieza agrega elemento por elemento a la pila
            pr.getRam().pushRam(objPagina.getCaracPila().get(i), objPagina.getCodigo());
            String palabra = (String) objPagina.getObjetosPila().get(i);
            aux = aux + " " + palabra;
        }
        System.out.println("despues del for");
        paginaArea.setText(aux);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVistaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox combo1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea paginaArea;
    private vista.panelRam panelRam1;
    // End of variables declaration//GEN-END:variables

    private void carga(String itemCount) {
   System.out.println("entro");
        
        int seleccionado = Integer.parseInt(itemCount) - 1;
        //encontrar el objeto
        objEncontrado = (Pagina) pr.getArbol().search(pr.getNombresDiscos().get(seleccionado));
        if (objEncontrado != null) {
            System.out.println("se encontro pagina con codigo de pila " + pr.getNombresDiscos().get(seleccionado));
            //se traera el contenido de la pila y se cargara a la ram

            cargarRam(objEncontrado);

        } else {
            System.out.println("no existe");
        }    }

}
